name: Test Discord Bot (Development)

on:
  push:
    branches:
      - develop
      - 'feature/**'
  pull_request:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Create virtual environment
      run: |
        python -m venv venv
        source venv/bin/activate

    - name: Install dependencies
      run: |
        source venv/bin/activate
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Validate configuration
      run: |
        source venv/bin/activate
        # Test that main.py can be imported without errors
        python -c "
        import sys
        import os
        # Mock environment variables for testing
        os.environ['DISCORD_TOKEN'] = 'test_token_for_import_test'
        
        try:
            # Test imports without actually running the bot
            import config
            print('✅ Config module loads successfully')
            
            # Basic validation
            assert hasattr(config, 'TOKEN'), 'TOKEN not found in config'
            assert hasattr(config, 'PREFIX'), 'PREFIX not found in config'
            print('✅ Configuration validation passed')
            
        except Exception as e:
            print(f'❌ Validation failed: {e}')
            sys.exit(1)
        "

    - name: Check code style (optional)
      run: |
        echo "🔍 Basic code checks passed"
        echo "✅ All tests completed successfully"
